### ISSUE TITLE
ASM: 'network nsg show' should give error instead of warning for non-existing nsg names

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#187]
Have attached the screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7702954/7cea4f0e-fe51-11e4-9d54-c3e7a194fc5a.png)

**Comment by romangromov** [comment]
Hi @HimanshuBri, we are using `warn` instead of `error` for all non-existing resources in ARM and ASM as well

**Comment by HimanshuBri** [comment]
@romangromov. but you changed it to error in the mentioned issue https://github.com/Azure/azure-xplat-cli/issues/1775

**Comment by romangromov** [comment]
Adding @anuchandy to put some light of this

**Comment by anuchandy** [comment]
@HimanshuBri @romangromov 

The pattern we followed so far is:

Show  command: show warn in case of non-existing resource
Delete command: throw exception in case of non-existing resource

In case of show we support --json option, when this is specified and when the resource does not exist we show "{ }" in case of scalar resource and "[]" in case of collection resource, this is to ensure scripts which uses pipes to parse json does not break. Since we are not throwing exception in this case (--json), we decided not to throw exception when no --json specified.

**Comment by HimanshuBri** [comment]
@romangromov. Closing the issue as per @anuchandy's comments
