### ISSUE TITLE
ASM: 'network vnet create' gives error when specifying only mandatory parameters

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#284]
Have attached the screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/8030412/5693e304-0de4-11e5-8306-997afd0d8678.png)

**Comment by romangromov** [comment]
Hi @HimanshuBri, sorry, we are not owns `ASM: network vnet` commands set, it's external.
Adding @anuchandy could you please confirm it's external? Thank you in advance

**Comment by HimanshuBri** [comment]
@romangromov. Ok. Thanks. But please have a look at https://github.com/MSOpenTech/azure-xplat-cli/issues/285 as it's a blocking issue for us.

**Comment by romangromov** [comment]
@HimanshuBri thank you for information, we are looking into this

**Comment by anuchandy** [comment]
@HimanshuBri thanks for validating this. Let me explain the pattern we follow in CLI.

In RDFE, a set of parameters are required to make the API calls, but in the corresponding CLI commands we will not make all of those parameters as positional. We accept minimal parameters via positional arguments and remaining required parameters via optional arguments. 

The optional arguments, if not provided and if required, then we prompt for these required parameters. But there is one exception: In some commands are there mutually exclusive required parameters. For example in case of vnet create location and affinity group  are mutually exclusive, but one of them is required. Since we have two options here we cannot prompt, we just throw exception saying one of them is required.

**Comment by HimanshuBri** [comment]
@anuchandy. Thanks for the clarification. I feel we can close this.
