### ISSUE TITLE
ASM: 'network local-network remove' giving error

### ISSUE THREAD

**Issue by roman-boltunov** [MSOpenTech/azure-xplat-cli#357]
Trying to remove local network which is associated with virtual network and getting this error:
<pre>
<code>
D:\Projects\azure-xplat-cli-roman\bin>node azure network local-network delete vnetForGate1lnet -q
info:    Executing command network local-network delete
+ Getting network configuration
+ Deleting local network site "vnetForGate1lnet"
error:   XML Schema validation error in network configuration. Missing LocalNetworkSiteRef 'vnetForGate1lnet'.
info:    Error information has been recorded to C:\Users\roman.boltunov\.azure\azure.err
error:   network local-network delete command failed
</code>
</pre>

**Comment by roman-boltunov** [comment]
We can fix this if we will look at the network configuration virtual networks and find if the local network is already associated with virtual network, then we will throw exception.

**Comment by anuchandy** [comment]
@roman-boltunov as you suggested I think it's good to check for the association and fail.

Just confirming, user can remove the association using the command:

vnet local-network remove [name] [local-network-name]

And try the command

network local-network remove

To remove the local network, right?

**Comment by roman-boltunov** [comment]
@anuchandy exactly, it works just as you mentioned.

**Comment by anuchandy** [comment]
@roman-boltunov thanks for confirming.

**Comment by roman-boltunov** [comment]
@anuchandy thanks, added check for association.
@sreekanthbs, I fixed this issue, could you please check that it works as expected?

**Comment by HimanshuBri** [comment]
@roman-boltunov  Yes its working fine now.
<pre>
<code>
C:\June\23June\2.45pm\azure-xplat-cli-dev-asm-network>node bin/azure network local-network delete CliTestlocNet7759 -q
info:    Executing command network local-network delete
+ Getting network configuration
error:   Cannot delete local network "CliTestlocNet7759" because it is associated with the virtual network "CliTestVnet18913"
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network local-network delete command failed
</code>
</pre>

**Comment by roman-boltunov** [comment]
@HimanshuBri thanks for confirming.
