### ISSUE TITLE
ARM: network route-table create not showing error  while creating a route-table with the existing route-table name

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#434]
![image](https://cloud.githubusercontent.com/assets/11171941/8746263/2e4645e2-2ca5-11e5-8655-d83360a56410.png)

**Comment by DeepakRajendranMsft** [comment]
Create essentially does a PUT on the RouteTable. so from the service side this is a valid scenario. We dont support PATCH and even updates have to happen only via a PUT. 

However, the second create must be blocked on the client, since it is already present. (so you have to do GET to check if the resource is present before doing a PUT)

**Comment by babumuralidharan** [comment]
@sreekanthbs is this still existing with the latest code base ? 

@MikhailTryakhov could you please take a look at this and let me know your comments ?

**Comment by sreekanthbs** [comment]
@babumuralidharan yes issue is still there,verified in https://github.com/MSOpenTech/azure-xplat-cli/tree/dev-arm-routes2 branch

![image](https://cloud.githubusercontent.com/assets/11171941/8844658/3f2d35fc-3135-11e5-82f9-2038022a3296.png)

**Comment by MikhailTryakhov** [comment]
@sreekanthbs  could you please review latest updates in dev-asm-network branch

**Comment by sreekanthbs** [comment]
@MikhailTryakhov yes now its working fine.Hence closing the issue
![image](https://cloud.githubusercontent.com/assets/11171941/8869210/e3902e50-31fe-11e5-9a4b-169f3dfdd288.png)
